[project]
authors = ["dsnjturtle <sebastian.t.kirchner@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Using mojo to solve AoC 2024"
name = "aoc_2024_mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
